### ISSUE TITLE
Float instead of a int for the min timer value ?

### ISSUE THREAD

**Issue by Huluti** [omines/antispam-bundle#13]
Hello :)

Thank you for your bundle, very useful!

Just one suggestion, could you make the `min` value of the `timer` feature a `float` instead of a `int` to allow values below 1?

Because on my case for urlr.me, I would prefer a value like 0.3 or 0.4 to make sure we don't prevent a human from quickly reducing his link.

What do you think?

**Comment by curry684** [comment]
I don't mind doing it, however I did make it an int on purpose as testing shows that over 90% of spam caught by the timer was submitted after 1 or 2 seconds. I don't think it'll actually help if you reduce it that low - roundtrips take longer than that for most connections.

**Comment by curry684** [comment]
Just realized it needed to be fixed anyway because the lower values can get into rounding issues, with 1.1 second counted as 2 in extreme cases.

**Comment by curry684** [comment]
Added and released, let me know if you run into issues   😄
