### ISSUE TITLE
Error in french translation

### ISSUE THREAD

**Issue by Moskito89** [omines/antispam-bundle#16]
When using version `0.1.5` Symfony throws two errors:

**1. In YamlFileLoader.php line 42:**
                                                                                                        

> The file "***/vendor/omines/antispam-bundle/translations/antispam+intl-icu.fr.yaml" does not contain valid YAML: Unexpected characters near "a pas pu être traité. Veuillez nous contacter si le problème persiste.'" at line 2 (near "stealthed: 'Le formulaire soumis n'a pas pu être traité. Veuillez nous contacter si le problème 

**2. In Parser.php line 757:**
                                                                                                    

> Unexpected characters near "a pas pu être traité. Veuillez nous contacter si le problème persiste.'"  at line 2 (near "stealthed: 'Le formulaire soumis n'a pas pu être traité. Veuillez nous contacter s i le problème persiste.'"). 

Unfortunately, I can't see what the problem is, but something seems to be wrong there.

**Comment by curry684** [comment]
Apologies, fixed in https://github.com/omines/antispam-bundle/pull/15#issuecomment-1826882775

I'll release a hotfix right away   😄

**Comment by curry684** [comment]
Please update to https://github.com/omines/antispam-bundle/releases/tag/0.1.6

**Comment by Moskito89** [comment]
Thank you! 👍
