### ISSUE TITLE
deprecation notice

### ISSUE THREAD

**Issue by Lorenzschaef** [omines/antispam-bundle#26]
We are currently trying the bundle with symfony 7 and are getting the following deprecaction notice:

> Method "Symfony\Component\HttpKernel\Bundle\Bundle::build()" might add "void" as a native return type declaration in the future. Do the same in child class "Omines\AntiSpamBundle\AntiSpamBundle" now to avoid errors or add an explicit @return annotation to suppress this message.

Just to let you know.

**Comment by curry684** [comment]
Fixed, thanks   👍
