### ISSUE TITLE
Feature: passive mode in configuration not working

### ISSUE THREAD

**Issue by kbond** [omines/antispam-bundle#4]
I'm not sure I completely understand passive mode. My thought was it didn't fail the validation but logged the "failure". This doesn't seem to be working - it still fails the form validation.

**Comment by kbond** [comment]
Sorry, didn't realize this bundle was still in heavy development.

I see you just added the passive mode earlier today and is unreleased but even using dev, making it true in my configuration profile still creates validation errors.

**Comment by curry684** [comment]
Sorry yes the passive mode was just implemented on validators today haha. Passive mode on forms is still to come, but kinda useless until the quarantine also works (next up) and the logging (after that). All require events (added today 😉 ).

I actually only tagged 0.1 today so our internal projects I'm using for testing can use stable packages. However that DOES mean that I'm actively doing release management, and releases should be stable and reliable. Just not feature complete yet.

**Comment by curry684** [comment]
So yes it's a feature, not a bug haha.

**Comment by kbond** [comment]
Looks like configuring passive in the profile's config works but not the global config yet?

**Comment by curry684** [comment]
Correct, already fixed locally.

**Comment by curry684** [comment]
It may be downright confusing right now though. The profiles have their own `stealth` and `passive` settings, which override the global config. In practice the global settings are only used by validators and form types outside of profile context. It may cause confusion that the global settings aren't doing anything if the profiles have defaults that override them (and at least for `stealth` for good reason).

Thinking on how to make that clearer and/or make more intuitive.

**Comment by kbond** [comment]
Ok, so the solution for the recipe is to enable passive on the default profile, correct?

> In practice the global settings are only used by validators and form types outside of profile context.

Ahh, ok, yeah, I didn't realize this was the intention.

**Comment by curry684** [comment]
> Ok, so the solution for the recipe is to enable passive on the default profile, correct?

Yes that would be the quick fix.

**Comment by curry684** [comment]
I think for `Stealth` the current situation is fine (global default false, profile default true).

However for `Passive` I think it makes more sense that the profiles default to `null`, meaning fall back to global. In that case the current recipe would still work, and that's intuitive methinks.

**Comment by kbond** [comment]
Let's first figure out the purpose of the _global_ options:
1. **passive**: my intuition told me this was a global override (for profiles/validators/types). The use case would be to enable globally in production to perhaps debug issues _or_ to disable in tests.
2. **stealth**: this one I have a hard time understanding the purpose. I can't think of why you'd want to configure this one globally - can you describe the use case? I wonder if this global option is required?

One idea would be to remove these two global options and replace with `enabled` (defaults to `true`). When `false`, all antispam configuration is ignored. This would be the easiest to reason about but... you'd lose logging/quarantining.

**Comment by kbond** [comment]
Thanks for the explanation, I understand. So what about the following for global config:
1. passive, keep as now
2. stealth, match passive behaviour - I feel it's confusing if the logic is different
3. enabled, add as a global option - this would be what we disable `when@test` in the recipe

**Comment by curry684** [comment]
It should make more sense now: https://omines.github.io/antispam-bundle/features/
