### ISSUE TITLE
Feature: fake success

### ISSUE THREAD

**Issue by kbond** [omines/antispam-bundle#7]
Instead of validation errors - even "stealth" ones, I think there should be a way to make it look like the form was submitted successfully. I'm not yet sure how this could work. Maybe an option to throw an exception that can be listened to and converted into/redirected to a "thank you for submitting page"

Ref: https://blog.stefanolaru.com/how-to-make-the-honeypot-field-more-effective ([specifically this](https://blog.stefanolaru.com/how-to-make-the-honeypot-field-more-effective#4-fake-happiness))

**Comment by curry684** [comment]
Considered this, but I don't yet really see a way to do this generically from the bundle - it would always require invasive code changes on the form handling end.

**Comment by curry684** [comment]
I have some ideas on how to utilize the results of running in passive mode, so currently this is blocked by #4

**Comment by kbond** [comment]
> but I don't yet really see a way to do this generically from the bundle

True enough, what I would do (which I believe is currently possible using events), is listen to the validation failed event, throw a custom exception, catch this exception and convert to a homepage redirect with a "thank you for filling out the form" flash message.

Like you say, pretty app specific.

**Comment by curry684** [comment]
"Fake pass" is now a thing  \o/

https://omines.github.io/antispam-bundle/advanced/#fake-pass
